# Targets
# The First target is the one build when there is nothing on make command line
#
all:
	chmod +x ./make.sh
	./make.sh

all-deb:
	chmod +x ./make-deb.sh
	./make-deb.sh

clean:
	chmod +x ./clean.sh
	./clean.sh

install:
	chmod +x ./install.sh
	./install.sh

uninstall:
	chmod +x ./uninstall.sh
	./uninstall.sh
